#!/usr/bin/env node
import { access, copyFile, mkdir, readFile } from 'node:fs/promises';
import { basename, join, resolve } from 'node:path';
import { loadAndValidate } from './validate-storyboard.mjs';
import { hash, parseArgs, readJson, run, writeJson } from './lib.mjs';

const args=parseArgs(process.argv.slice(2));if(!args._[0]){console.error('Usage: node capture-scenes.mjs <storyboard.json> --base-url <url> [--output dir] [--reuse-screenshots] [--update-baseline]');process.exit(2);}
const storyboard=await loadAndValidate(resolve(args._[0])),baseUrl=args['base-url']??storyboard.baseUrl;if(!baseUrl&&storyboard.scenes.some(s=>!/^https?:\/\//.test(s.route)))throw new Error('A base URL is required for relative scene routes');const output=resolve(args.output??join(process.cwd(),'tutorial-output')),resolvedPath=join(output,'storyboard.resolved.json'),screenshots=join(output,'screenshots'),baselineDir=join(output,'baseline'),diffDir=join(output,'visual-diffs');
if(args['reuse-screenshots']&&await exists(resolvedPath)){console.log(`Reused screenshots from ${resolvedPath}`);process.exit(0);}await Promise.all([mkdir(screenshots,{recursive:true}),mkdir(baselineDir,{recursive:true}),mkdir(diffDir,{recursive:true})]);
process.env.PLAYWRIGHT_BROWSERS_PATH??='0';let chromium;try{({chromium}=await import('playwright'));}catch{throw new Error('Playwright runtime is unavailable. Run npm ci and npm run setup in the skill directory.');}
const quality=await readJson(join(output,'quality-report.json'),{status:'ok'});quality.warnings??=[];quality.errors??=[];quality.visualDiffs??=[];const browser=await chromium.launch({headless:true});
try{const v=storyboard.viewport,context=await browser.newContext({viewport:{width:v.width,height:v.height},deviceScaleFactor:v.deviceScaleFactor??1,reducedMotion:'reduce',timezoneId:'UTC',...(args['storage-state']?{storageState:resolve(args['storage-state'])}:{})}),page=await context.newPage(),resolvedScenes=[];if(storyboard.fixtures)await context.addInitScript(seedFixtures,storyboard.fixtures);
for(const[index,scene]of storyboard.scenes.entries()){
  const url=/^https?:\/\//.test(scene.route)?scene.route:new URL(scene.route,ensureSlash(baseUrl)).href;try{await page.goto(url,{waitUntil:'networkidle',timeout:Number(args.timeout??30000)});}catch(error){throw new Error(`Scene ${scene.id}: page load failed for ${url}: ${error.message}`);}await page.addStyleTag({content:'*,*::before,*::after{animation-duration:0s!important;transition-duration:0s!important;caret-color:transparent!important}'});if(scene.readySelector)await(await requireLocator(page,scene.readySelector,scene.id,undefined,false)).waitFor({state:'visible',timeout:Number(args.timeout??30000)});
  for(const[prepareIndex,prepare]of(scene.prepare??[]).entries()){const geometry=await resolveGeometry(page,prepare,scene.id,`prepare ${prepareIndex}`);await perform(page,prepare,geometry,scene.id,`prepare ${prepareIndex}`);}
  const file=join(screenshots,`scene-${String(index+1).padStart(3,'0')}.png`);await page.screenshot({path:file,animations:'disabled'});if(await isBlank(file)){quality.errors.push({code:'blank-screenshot',scene:scene.id});throw new Error(`Scene ${scene.id}: screenshot appears blank`);}await compareBaseline(file,join(baselineDir,basename(file)),join(diffDir,basename(file)),scene.id,quality,Boolean(args['update-baseline']));
  const actions=[];for(const[actionIndex,action]of scene.actions.entries()){const geometry=await resolveGeometry(page,action,scene.id,actionIndex);actions.push({...action,id:action.id??`action-${actionIndex+1}`,...geometry});await perform(page,action,geometry,scene.id,actionIndex);}resolvedScenes.push({...scene,screenshot:`screenshots/${basename(file)}`,actions});
}
await writeJson(resolvedPath,{...storyboard,language:storyboard.language??'de',baseUrl:baseUrl??storyboard.baseUrl,scenes:resolvedScenes});quality.status=quality.errors.length?'error':quality.warnings.length?'warning':'ok';await writeJson(join(output,'quality-report.json'),quality);console.log(`Captured ${resolvedScenes.length} scene(s); quality ${quality.status}`);await context.close();}finally{await browser.close();}

async function requireLocator(page,selector,sceneId,actionIndex,allowMultiple){const count=await page.locator(selector).count(),label=`Scene ${sceneId}${actionIndex===undefined?'':` action ${actionIndex}`}`;if(count===0)throw new Error(`${label}: selector not found: ${selector}`);if(count>1&&!allowMultiple)throw new Error(`${label}: selector matched ${count} elements; use a unique selector or allowMultiple`);return page.locator(selector).first();}
async function resolveGeometry(page,action,sceneId,index){if(action.target){const locator=await requireLocator(page,action.target,sceneId,index,action.allowMultiple);await locator.scrollIntoViewIfNeeded();const rect=await locator.boundingBox();if(!rect)throw new Error(`Scene ${sceneId} action ${index}: target is not visible: ${action.target}`);const viewport=page.viewportSize();if(rect.x<0||rect.y<0||rect.x+rect.width>viewport.width||rect.y+rect.height>viewport.height)throw new Error(`Scene ${sceneId} action ${index}: target is outside viewport`);return{rect,x:rect.x+rect.width/2,y:rect.y+rect.height/2};}return Number.isFinite(action.x)?{x:action.x,y:action.y}:{};}
async function perform(page,action,point,sceneId,index){try{if(action.type==='move')await page.mouse.move(point.x,point.y,{steps:12});if(action.type==='click')await page.mouse.click(point.x,point.y,{button:action.button??'left'});if(action.type==='fill')await page.locator(action.target).first().fill(action.value);if(action.type==='press')await page.locator(action.target).first().press(action.key);if(action.type==='wait')await page.waitForTimeout((action.duration??.5)*1000);}catch(error){throw new Error(`Scene ${sceneId} action ${index} (${action.type}) failed: ${error.message}`);}}
async function compareBaseline(current,baseline,diff,scene,quality,update){if(update||!await exists(baseline)){await copyFile(current,baseline);return;}const[a,b]=await Promise.all([readFile(current),readFile(baseline)]);if(hash(a)!==hash(b)){await run('ffmpeg',['-v','error','-i',baseline,'-i',current,'-filter_complex','[0:v][1:v]blend=all_mode=difference','-frames:v','1','-y',diff]);quality.warnings.push({code:'visual-change',scene,diff:`visual-diffs/${basename(diff)}`});quality.visualDiffs.push({scene,diff:`visual-diffs/${basename(diff)}`});}}
async function isBlank(file){const out=await run('ffmpeg',['-hide_banner','-i',file,'-vf','signalstats,metadata=print:file=-','-frames:v','1','-f','null','-'],{includeStderr:true});const min=Number(out.match(/YMIN=([\d.]+)/)?.[1]),max=Number(out.match(/YMAX=([\d.]+)/)?.[1]);return Number.isFinite(min)&&Number.isFinite(max)&&max-min<2;}
async function exists(path){try{await access(path);return true;}catch{return false;}}function ensureSlash(url){return url.endsWith('/')?url:`${url}/`;}
async function seedFixtures(fixtures){const write=(store,values)=>{if(!values)return;for(const[key,value]of Object.entries(values))store.setItem(key,typeof value==='string'?value:JSON.stringify(value));};if(fixtures.window)for(const[key,value]of Object.entries(fixtures.window))window[key]=value;write(window.localStorage,fixtures.localStorage);write(window.sessionStorage,fixtures.sessionStorage);}
