#!/usr/bin/env node
import { mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import { basename, join, resolve } from 'node:path';
import { loadAndValidate } from './validate-storyboard.mjs';
import { copyEnsured, hash, loadSkillEnv, speechEndpoint, narrationSegments, parseArgs, run, stamp, writeJson } from './lib.mjs';

const args=parseArgs(process.argv.slice(2));if(!args._[0]){console.error('Usage: node generate-voice.mjs <storyboard.json> [--output dir] [--language de] [--mock] [--force]');process.exit(2);}
const envKeys=loadSkillEnv(import.meta.url);if(envKeys.length)console.log(`Loaded ${envKeys.join(', ')} from the skill ENV file`);
const storyboard=await loadAndValidate(resolve(args._[0]));const output=resolve(args.output??join(process.cwd(),'tutorial-output'));const language=(args.language??storyboard.language??'de')==='auto'?'de':(args.language??storyboard.language??'de');
const ttsSpeed=speedValue(args['tts-speed']??storyboard.ttsSpeed??1.2);
const audioDir=join(output,'audio'),segmentDir=join(audioDir,'segments'),cacheDir=join(output,'.cache','audio');await Promise.all([mkdir(segmentDir,{recursive:true}),mkdir(cacheDir,{recursive:true})]);
const manifest={storyboardVersion:storyboard.version??1,title:storyboard.title,language,scenes:[],cache:{audioHits:0,audioMisses:0},tts:{characters:0,requests:0,fallbacks:0,speed:ttsSpeed}};let cursor=0,cue=1;const cues=[];
for(const[index,scene]of storyboard.scenes.entries()){
  const segments=narrationSegments(scene,language);if(!segments.length)throw new Error(`Scene ${scene.id}: no narration for language ${language}`);const rendered=[];let sceneCursor=0;
  for(const[segmentIndex,segment]of segments.entries()){
    const segmentFile=join(segmentDir,`${String(index+1).padStart(3,'0')}-${String(segmentIndex+1).padStart(2,'0')}-${segment.id}.wav`);const candidates=args.mock?[{model:'mock-tts',voice:'silent'}]:[{model:args.model??'gemini-3.8-flash-lite-tts',voice:args.voice??'Kore'},{model:args['fallback-model']??'gpt-4o-mini-tts',voice:args['fallback-voice']??'cedar'}];let accepted,lastError;
    for(const[candidateIndex,candidate]of candidates.entries())try{
      const cacheKey=hash({v:4,text:segment.text,language,speed:ttsSpeed,...candidate,mock:Boolean(args.mock)}),cached=join(cacheDir,`${cacheKey}.wav`);let cacheHit=false;
      if(!args.force&&!(args.scene===scene.id)&&await exists(cached)){await copyEnsured(cached,segmentFile);cacheHit=true;manifest.cache.audioHits++;}
      else{if(args.mock)await createMockWav(segmentFile,mockDuration(segment.text));else{await requestSpeech(segmentFile,segment.text,candidate,language);manifest.tts.requests++;}manifest.cache.audioMisses++;}
      await unwrapNestedWav(segmentFile);assertWav(await readFile(segmentFile));await applySpeed(segmentFile,ttsSpeed);let duration=await probeDuration(segmentFile),tailTrimmed=false;if(await hasTailBurst(segmentFile,duration)){await cleanTail(segmentFile,duration);duration=await probeDuration(segmentFile);tailTrimmed=true;if(await hasTailBurst(segmentFile,duration))throw new Error('tail burst remains after cleanup');}if(!cacheHit)await copyEnsured(segmentFile,cached);
      accepted={...candidate,id:segment.id,text:segment.text,audio:`audio/segments/${basename(segmentFile)}`,start:sceneCursor,end:sceneCursor+duration,duration,tailTrimmed,cacheHit};if(candidateIndex>0)manifest.tts.fallbacks++;break;
    }catch(error){lastError=error;}
    if(!accepted)throw new Error(`Scene ${scene.id}, segment ${segment.id}: TTS failed: ${lastError?.message??'unknown error'}`);rendered.push(accepted);sceneCursor=accepted.end;manifest.tts.characters+=segment.text.length;
  }
  const sceneFile=join(audioDir,`scene-${String(index+1).padStart(3,'0')}.wav`);await concatWavs(rendered.map(s=>join(output,s.audio)),sceneFile);const duration=await probeDuration(sceneFile);const start=cursor,end=start+duration;
  for(const segment of rendered){cues.push({index:cue++,start:start+segment.start,end:start+segment.end,text:segment.text});}
  manifest.scenes.push({id:scene.id,narration:rendered.map(s=>s.text).join(' '),audio:`audio/${basename(sceneFile)}`,start,end,duration,segments:rendered,model:[...new Set(rendered.map(s=>s.model))].join(','),voice:[...new Set(rendered.map(s=>s.voice))].join(','),tailTrimmed:rendered.some(s=>s.tailTrimmed)});cursor=end;
}
manifest.duration=cursor;await writeJson(join(output,'tutorial-manifest.json'),manifest);await writeFile(join(output,'tutorial.vtt'),`WEBVTT\n\n${cues.map(c=>`${c.index}\n${stamp(c.start)} --> ${stamp(c.end)}\n${c.text}\n`).join('\n')}`);console.log(`Generated ${manifest.scenes.length} scene(s), ${cues.length} narration segment(s); cache ${manifest.cache.audioHits} hit(s)`);

async function requestSpeech(file,input,candidate,language){const base=process.env.AI_HUB_BASEURL,key=process.env.AI_HUB_APIKEY;if(!base||!key)throw new Error('AI_HUB_BASEURL and AI_HUB_APIKEY are required; put them in the skill ENV file');const endpoint=speechEndpoint(base);let response;try{response=await fetch(endpoint,{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model:candidate.model,voice:candidate.voice,input,response_format:'wav',language})});}catch(error){throw new Error(`cannot reach ${endpoint}: ${error.message}`);}if(!response.ok)throw new Error(`${endpoint} returned HTTP ${response.status}`);const buffer=Buffer.from(await response.arrayBuffer());if(buffer.length<12||buffer.toString('latin1',0,4)!=='RIFF')throw new Error(`${endpoint} returned ${response.headers.get('content-type')??'an unknown content type'} instead of a WAV file (${buffer.length} bytes, starts with ${JSON.stringify(buffer.subarray(0,4).toString('latin1'))})`);await writeFile(file,buffer);}
async function unwrapNestedWav(file){const buffer=await readFile(file);const dataOffset=waveDataOffset(buffer);if(dataOffset===null)return;const embedded=buffer.subarray(dataOffset);if(embedded.length<12||embedded.toString('ascii',0,4)!=='RIFF'||embedded.toString('ascii',8,12)!=='WAVE')return;const size=embedded.readUInt32LE(4)+8;if(size<44||size>embedded.length)throw new Error('nested WAV has an invalid length');await writeFile(file,embedded.subarray(0,size));}
function waveDataOffset(buffer){if(buffer.length<12||buffer.toString('ascii',0,4)!=='RIFF'||buffer.toString('ascii',8,12)!=='WAVE')return null;let offset=12;while(offset+8<=buffer.length){const id=buffer.toString('ascii',offset,offset+4),size=buffer.readUInt32LE(offset+4),payload=offset+8;if(id==='data')return payload;offset=payload+size+(size%2);}return null;}
function assertWav(buffer){if(buffer.length<44||buffer.toString('ascii',0,4)!=='RIFF'||buffer.toString('ascii',8,12)!=='WAVE')throw new Error('response is not a valid RIFF/WAVE file');}function mockDuration(text){return Math.max(1.2,Math.min(15,text.trim().length/12));}async function createMockWav(file,duration){await run('ffmpeg',['-v','error','-f','lavfi','-i','anullsrc=r=24000:cl=mono','-t',String(duration),'-c:a','pcm_s16le','-y',file]);}
async function concatWavs(files,target){const inputs=files.flatMap(file=>['-i',file]);await run('ffmpeg',['-v','error',...inputs,'-filter_complex',`${files.map((_,i)=>`[${i}:a]`).join('')}concat=n=${files.length}:v=0:a=1[out]`,'-map','[out]','-c:a','pcm_s16le','-y',target]);}
async function probeDuration(file){const value=Number((await run('ffprobe',['-v','error','-show_entries','format=duration','-of','default=nw=1:nk=1',file])).trim());if(!(value>0))throw new Error('ffprobe returned zero or invalid duration');return value;}
async function peakDb(file,start,duration){const out=await run('ffmpeg',['-hide_banner','-ss',String(Math.max(0,start)),'-t',String(duration),'-i',file,'-af','volumedetect','-f','null','-'],{includeStderr:true});const match=out.match(/max_volume:\s*(-?(?:\d+(?:\.\d+)?|inf)) dB/);return match?Number(match[1]):-Infinity;}
async function hasTailBurst(file,duration){if(duration<.35)return false;const tail=await peakDb(file,duration-.25,.25),before=await peakDb(file,Math.max(0,duration-.75),Math.min(.5,duration-.25));return tail>=-.5&&tail-before>=6;}
async function cleanTail(file,duration){const cleaned=`${file}.clean.wav`,target=Math.max(.1,duration-.22),fadeStart=Math.max(0,target-.08);await run('ffmpeg',['-v','error','-i',file,'-af',`atrim=0:${target},afade=t=out:st=${fadeStart}:d=0.08`,'-c:a','pcm_s16le','-y',cleaned]);await rename(cleaned,file);}async function exists(path){try{await readFile(path);return true;}catch{return false;}}
function speedValue(value){const speed=Number(value);if(!Number.isFinite(speed)||speed<.5||speed>3)throw new Error('TTS speed must be a number between 0.5 and 3');return speed;}
async function applySpeed(file,speed){if(!(speed>1.0001))return;const chain=[];let remaining=speed;while(remaining>2){chain.push('atempo=2');remaining/=2;}chain.push('atempo='+remaining.toFixed(4));const sped=`${file}.speed.wav`;await run('ffmpeg',['-v','error','-i',file,'-af',chain.join(','),'-c:a','pcm_s16le','-y',sped]);await rename(sped,file);}
