import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { copyFile, mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawn } from 'node:child_process';

export function parseArgs(values) { const out = { _: [] }; for (let i = 0; i < values.length; i++) { const value = values[i]; if (!value.startsWith('--')) out._.push(value); else { const key = value.slice(2); out[key] = values[i + 1] && !values[i + 1].startsWith('--') ? values[++i] : true; } } return out; }
export function narrationSegments(scene, language = 'de') { const source = scene.narration; const selected = typeof source === 'string' ? source : source?.[language] ?? source?.de; if (typeof selected === 'string') return [{ id: 'narration', text: selected }]; if (!Array.isArray(selected)) return []; return selected.map((segment, index) => typeof segment === 'string' ? { id: `segment-${index + 1}`, text: segment } : { id: segment.id ?? `segment-${index + 1}`, text: segment.text }); }
export function hash(value) { const input = typeof value === 'string' || Buffer.isBuffer(value) ? value : JSON.stringify(value); return createHash('sha256').update(input).digest('hex'); }
export async function readJson(path, fallback) { try { return JSON.parse(await readFile(path, 'utf8')); } catch (error) { if (fallback !== undefined && error.code === 'ENOENT') return fallback; throw error; } }
export async function writeJson(path, value) { await mkdir(dirname(path), { recursive: true }); await writeFile(path, `${JSON.stringify(value, null, 2)}\n`); }
export async function copyEnsured(from, to) { await mkdir(dirname(to), { recursive: true }); await copyFile(from, to); }
export function run(command, args, { includeStderr = false, inherit = false, env } = {}) { return new Promise((resolve, reject) => { const child = spawn(command, args, { stdio: inherit ? 'inherit' : 'pipe', env: env ?? process.env }); if (inherit) { child.on('error', reject); child.on('close', code => code === 0 ? resolve('') : reject(new Error(`${command} failed with exit code ${code}`))); return; } let stdout = '', stderr = ''; child.stdout.on('data', data => stdout += data); child.stderr.on('data', data => stderr += data); child.on('error', error => reject(new Error(`${command} is unavailable: ${error.message}`))); child.on('close', code => code === 0 ? resolve(includeStderr ? stdout + stderr : stdout) : reject(new Error(`${command} failed (${code}): ${stderr.trim()}`))); }); }
export function stamp(value) { const ms = Math.round(value * 1000); const h = Math.floor(ms / 3600000); const m = Math.floor(ms % 3600000 / 60000); const s = Math.floor(ms % 60000 / 1000); return `${String(h).padStart(2, '0')}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}.${String(ms % 1000).padStart(3, '0')}`; }
export function loadEnvFile(file) { const loaded = []; let text; try { text = readFileSync(file, 'utf8'); } catch (error) { if (error.code === 'ENOENT') return loaded; throw error; } for (const raw of text.split(/\r?\n/)) { const line = raw.trim(); if (!line || line.startsWith('#')) continue; const match = /^(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/.exec(line); if (!match) continue; const key = match[1]; let value = match[2].trim(); if (value.length > 1 && ((value.startsWith('\"') && value.endsWith('\"')) || (value.startsWith("'") && value.endsWith("'")))) value = value.slice(1, -1); if (!value || process.env[key] !== undefined) continue; process.env[key] = value; loaded.push(key); } return loaded; }
export function loadSkillEnv(importMetaUrl) { return loadEnvFile(resolve(dirname(fileURLToPath(importMetaUrl)), '..', 'ENV')); }
export function speechEndpoint(base) { const raw = String(base ?? '').trim().replace(/\/+$/, ''); if (!raw) throw new Error('AI_HUB_BASEURL is empty'); if (/\/audio\/speech$/i.test(raw)) return raw; let url; try { url = new URL(raw); } catch { throw new Error(`AI_HUB_BASEURL is not a valid URL: ${raw}`); } if (!['http:', 'https:'].includes(url.protocol)) throw new Error(`AI_HUB_BASEURL must be an http or https URL: ${raw}`); const path = url.pathname.replace(/\/+$/, ''); return (path ? url.origin + path : url.origin + '/v1') + '/audio/speech' + url.search; }
